name: grossery
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
  
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/images/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/images/play_store_512.png"
  min_sdk_android: 21